import Head from 'next/head'
import Link from 'next/link'
import Clients from '../components/Clients'
import Contact from '../components/Contact'
import Filming from '../components/Filming'
import Header from '../components/Header'
import HeroSection from '../components/HeroSection'
import PostProduction from '../components/PostProduction'
import PreProduction from '../components/PreProduction'
import Production from '../components/Production'
import Products from '../components/Products'
import Samples from '../components/Samples'
import WhatWeDo from '../components/WhatWeDo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Website clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='flex'>
        <div className='h-screen bg-black hidden sm:block sm:max-w-[226px]'>
          <img src="https://web.archive.org/web/20181127040815im_/http://lucentpics.com/assets/images/logo.png" alt="" />
          <div className='flex items-center  pl-[20.4px] pr-[6.8px] py-[6.8px] bg-[#121212] text-white'>
            <p className='text-[11px] leading-[13px] font-medium md:text-[14.14px] md:leading-[26px]'>Kathmandu,Nepal</p>
          </div>
          <div className='w-full bg-[#b27234] mt-1'>
            <Link href={"#hero"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px]  md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#121212] ">Home</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#what_we_do"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px] md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#fff] ">What We do</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#products"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px] md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#fff] ">Product</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#pre_production"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px] md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#fff] ">Services</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#filming"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px] md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#fff] ">Filming in Nepal</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#sample"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px]  md:text-[11.52px] md:leading-[22px]leading-[16px] text-[#fff] ">Works</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#clients"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px] md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#fff] ">Clients</Link>
          </div>
          <div className='w-full hover:bg-[#b27234] '>
            <Link href={"#contact"} className="pl-[20.4px] pr-[13.6px] py-[6.8px] text-[11px] md:text-[11.52px] md:leading-[22px] leading-[16px] text-[#fff] ">Contact Us</Link>
          </div>
        </div>
        <div className=' overflow-x-hidden snap-y snap-mandatory overflow-scroll h-screen main sm:flex-1'>
          <Header />
          <section id='hero' className='h-screen snap-center'>
            <HeroSection />
          </section>
          <section className='snap-start' id='what_we_do'>
            <WhatWeDo />
          </section>
          <section className='h-screen snap-center' id='products'>
            <Products />
          </section>
          <section className='h-screen bg-red-500 snap-center' id='pre_production'>
            <PreProduction />
          </section>
          <section className='h-screen bg-red-500 snap-center' id='production'>
            <Production />
          </section>
          <section className='h-screen bg-red-500 snap-center' id='post_production'>
            <PostProduction />
          </section>
          <section className='h-screen bg-red-300 snap-center' id='filming'>
            <Filming />
          </section>
          <section className='h-screen snap-center ' id='sample'>
            <Samples />
          </section>
          <section className='h-screen bg-purple-100 overflow-hidden snap-center' id='clients'>
            <Clients />
          </section>
          <section className='h-screen bg-red-400 snap-center' id='contact'>
            <Contact />
          </section>
        </div>
      </div>
    </>
  )
}
